### ISSUE TITLE
Documentation about wallabag-cli

### ISSUE THREAD

**Issue by nicosomb** [Nepochal/wallabag-cli#1]
Hello @Nepochal! 

Thank you for this tool 👍 
Can you add documentation in the README file please? 

Nicolas

**Comment by Nepochal** [comment]
Hello Nicolas,

this tool is far away from being suitable. So documentation has a low priority for me now. But I will add a documentation once I made some progress :)

Michael

**Comment by Nepochal** [comment]
I added some documentation files in the docs folder. If there is something missing feel free to open a new issue.

Michael

**Comment by nicosomb** [comment]
👍
