### ISSUE TITLE
config file 

### ISSUE THREAD

**Issue by ghost** [Nepochal/wallabag-cli#5]
I could not create or pass config file ?

`Could not find a valid config. Would you like to create it now? [Y/n] Y
Error: Could not load or create the config file.`

I try to pass a config file to wallabag , it not work !

`wwallabag --config=/my-path/.wallabag-cli`

error 

`Invalid option "--config=/my-path/.wallabag-cli".
Use "wallabag" to see a full list of options.`

**Comment by jludwig** [comment]
I made the following edit to get it to work:

```
diff --git a/wallabag/wallabag.py b/wallabag/wallabag.py
index 9f243e8..ea6c368 100755
--- a/wallabag/wallabag.py
+++ b/wallabag/wallabag.py
@@ -28,13 +28,12 @@ if platform.system() == "Windows":
     if "65001" not in codepage:
         subprocess.check_output(['chcp', '65001'], shell=True)
 
-# Determine custom config path
-for arg in argv:
-    if arg[0:9] == "--config=":
-        conf.set_path(arg[9:len(arg)])
-
 # Determine command or general standalone option
-if len(argv) == 1 or argv[1] in {'-h', '--help'}:
+if argv[1][0:9] == '--config=':
+    conf.set_path(argv[1][9:len(argv[1])])
+    if argv[2] in ["config", "add", "update", "read", "star", "delete", "list", "show"]:
+        command = argv[2]
+elif len(argv) == 1 or argv[1] in {'-h', '--help'}:
     help(argv[0])
     exit(0)
 elif argv[1] in {'-v', '--version'}:
```

It works, but it's not ideal. A refactor of the option / command building section would be better, which is why I'm not opening a PR for this.

**Comment by Nepochal** [comment]
I implmenented the solution from jludwig. Thanks a lot. It will be in the next hotfix release.
